### PR TITLE
LMO repeat bug fix in example script

### PR DESCRIPTION
**Pull request by gideonite**
Gotta use a plus instead of a minus. Also added an import to datasets which wasn't working properly on my laptop.

Here's the current output:
lmo_repeats

### CODE REVIEW

**Comment by gideonite** [comment]
I have some additional minor improvements that I can merge in. Should I tack them on to this PR or open a new one? @fabianp

**Comment by fabianp** [comment]
Awesome, merged!

**Comment by fabianp** [comment]
Please open a different PR if the change is big. Otherwise you can just push directly, I'm about to give you write access

**Comment by fabianp** [comment]
In a while (~1h) it should automatically update https://storage.googleapis.com/copt/auto_examples/frank_wolfe/plot_vertex_overlap.html

Fingers crossed

**Pull request merged**
