### PR TITLE
FIX np.NaN is not available anymore in numpy2.0

### PR DESCRIPTION
**Pull request by tomMoral**
Just notived a failure with numpy 2.0.
This is a quick fix for the failure I observed.

### CODE REVIEW

**Comment by tomMoral** [comment]
Not sure how to cope with the missing `AttributeError: `scipy.optimize.optimize` has no attribute `MemoizeJac`

**Comment by arokem** [comment]
This seems relevant: https://github.com/scipy/scipy/issues/17572#issuecomment-1368482400

**Comment by arokem** [comment]
Looks like this works: 

```
from scipy.optimize._optimize import MemoizeJac
```

**Comment by arokem** [comment]
Looks good! Unless anyone objects, I can go ahead and merge it in a couple of days.

**Comment by tomMoral** [comment]
Great :)

Note that we saw this failure in the test of our benchmark on logreg l2, where we benchmark `copt` against other solvers :)
https://github.com/benchopt/benchmark_logreg_l2

It has been a while since we updated the `copt` solver so if you think we can [improve its performances](https://benchopt.github.io/results/benchmark_logreg_l2_benchmark_logreg_l2_benchopt_run_2021-03-18_02h11m46.html), feel free to contribute updates to the [`copt solver`](https://github.com/benchopt/benchmark_logreg_l2/blob/main/solvers/copt.py)

**Comment by fabianp** [comment]
thanks all!

**Comment by arokem** [comment]
Hey @fabianp : any chance to put out a pypi release (0.9.2?) that includes this fix? Thanks!

**Comment by fabianp** [comment]
should be done now, sorry for the delay

**Pull request merged**
